In [147]:
import pandas as pd

religion = pd.read_csv("clean_religions.csv")
gdp = pd.read_csv("gdp_data_cleaned_file.csv")
hdi = pd.read_csv("hdi_long.csv")
conflict1 = pd.read_csv("conflict_countries.csv")
regions= pd.read_csv("JME_Regional-Classifications.csv", sep = ";")
conflict2 = pd.read_csv("Conflict_Site_from_2005.csv", sep = ";")

In [228]:
religion = religion.rename(columns={"Country":"country","Year":"year"})
conflict1 = conflict1.rename(columns={"Country":"country","Year":"year"})
conflict2 = conflict2.rename(columns={"Country":"country","Year":"year"})
regions.columns = (
        regions.columns
        .str.strip()
        .str.lower()
        .str.replace(r"[^\w\s]", "", regex=True)
        .str.replace(" ", "_"))
regions

,iso_code,country,un_region,un_sub_region,sdg_region,development_regions,unicef_region,unicef_subregions,who_region,world_bank_income_groups,world_bank_income_groups_combined,world_bank_regions
0,AFG,Afghanistan,Asia,Southern Asia,Central Asia and Southern Asia,Least Developed,ROSA,SA,EMRO,Low Income,Low Income,South Asia
1,ALB,Albania,Europe,Southern Europe,Northern America and Europe,More Developed,ECA,EECA,EURO,Upper Middle Income,Middle Income,Europe & Central Asia
2,DZA,Algeria,Africa,Northern Africa,Western Asia and Northern Africa,Less Developed,MENA,MENA,AFRO,Upper Middle Income,Middle Income,Middle East & North Africa
3,AND,Andorra,Europe,Southern Europe,Northern America and Europe,More Developed,ECA,WE,EURO,High Income,High Income,Europe & Central Asia
4,AGO,Angola,Africa,Middle Africa,Sub-Saharan Africa,Least Developed,SSA,ESA,AFRO,Lower Middle Income,Middle Income,Sub-Saharan Africa
...,...,...,...,...,...,...,...,...,...,...,...,...
201,ZWE,Zimbabwe,Africa,Eastern Africa,Sub-Saharan Africa,Less Developed,SSA,ESA,AFRO,Low Income,Low Income,Sub-Saharan Africa
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,1 UNICEF regional abbreviations and full names...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,2 WHO regional abbreviations and full names: A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,3 Based on FY18 World Bank income classification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [229]:
conflict1["conflict_present"] = 1
conflict2["conflict_present"] = 1

In [230]:
conflict = pd.concat([conflict1, conflict2], axis=0, join="outer")
conflict.drop_duplicates(inplace=True)
conflict

     year                           country  conflict_present
0    1946  Bolivia (Plurinational State of)                 1
1    1952  Bolivia (Plurinational State of)                 1
2    1967  Bolivia (Plurinational State of)                 1
3    1946                          Cambodia                 1
4    1947                          Cambodia                 1
..    ...                               ...               ...
509  2007                           Lebanon                 1
511  2021                              Iraq                 1
512  2022                              Iraq                 1
513  2023                              Iraq                 1
514  2024                              Iraq                 1

[1915 rows x 3 columns]

In [231]:
merged = religion.merge(gdp, on=["country","year"],how="left")

In [232]:
merged.tail()

,index,year,country,Christianity,Judaism,Islam,Buddhism,Hindu,Shinto,Confus_Tao,code,gdp
2289,2303,1990,Samoa,159500,0,37,15,0,0,0,WSM,1.257663e+08
2290,2304,1995,Samoa,161677,0,43,16,0,0,0,WSM,2.248657e+08
2291,2305,2000,Samoa,174600,0,50,18,0,0,0,WSM,2.588561e+08
2292,2306,2005,Samoa,177510,0,58,18,0,0,0,WSM,4.768018e+08
2293,2307,2010,Samoa,180140,0,61,19,0,0,0,WSM,6.802609e+08

In [233]:
merged = merged.merge(hdi, on=["country","year"],how="left")
merged = merged.merge(conflict, on=["country","year"],how="left")

merged["country"] = merged["country"].str.title()
regions["country"] = regions["country"].str.title()

merged = merged.merge(regions, on=["country", "un_region"],how="left")

In [234]:
merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 2294 entries, 0 to 2293
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   index                              2294 non-null   int64
 1   year                               2294 non-null   int64
 2   country                            2294 non-null   str
 3   Christianity                       2294 non-null   int64
 4   Judaism                            2294 non-null   int64
 5   Islam                              2294 non-null   int64
 6   Buddhism                           2294 non-null   int64
 7   Hindu                              2294 non-null   int64
 8   Shinto                             2294 non-null   int64
 9   Confus_Tao                         2294 non-null   int64
 10  code                               1030 non-null   str
 11  gdp                                1030 non-null   float64
 12  un_region                          618 non-null    str
 13  hdi                                618 non-null    float64
 14  conflict_present                   301 non-null    float64
 15  iso_code                           618 non-null    str
 16  un_sub_region                      618 non-null    str
 17  sdg_region                         618 non-null    str
 18  development_regions                618 non-null    str
 19  unicef_region                      612 non-null    str
 20  unicef_subregions                  612 non-null    str
 21  who_region                         618 non-null    str
 22  world_bank_income_groups           618 non-null    str
 23  world_bank_income_groups_combined  618 non-null    str
 24  world_bank_regions                 618 non-null    str
dtypes: float64(3), int64(9), str(13)
memory usage: 448.2 KB

In [235]:
display(merged)

,index,year,country,Christianity,Judaism,Islam,Buddhism,Hindu,Shinto,Confus_Tao,...,iso_code,un_sub_region,sdg_region,development_regions,unicef_region,unicef_subregions,who_region,world_bank_income_groups,world_bank_income_groups_combined,world_bank_regions
0,0,1945,United States,110265118,4641182,0,1601218,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1950,United States,122994019,6090837,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1955,United States,134001770,5333332,0,90173,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1960,United States,150234347,5500000,0,2012131,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1965,United States,167515758,5600000,0,1080892,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2303,1990,Samoa,159500,0,37,15,0,0,0,...,WSM,Polynesia,Oceania excluding Australia and New Zealand,Less Developed,EAPRO,EAP,WPRO,Upper Middle Income,Middle Income,East Asia & Pacific
2290,2304,1995,Samoa,161677,0,43,16,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2291,2305,2000,Samoa,174600,0,50,18,0,0,0,...,WSM,Polynesia,Oceania excluding Australia and New Zealand,Less Developed,EAPRO,EAP,WPRO,Upper Middle Income,Middle Income,East Asia & Pacific
2292,2306,2005,Samoa,177510,0,58,18,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2293,2307,2010,Samoa,180140,0,61,19,0,0,0,...,WSM,Polynesia,Oceania excluding Australia and New Zealand,Less Developed,EAPRO,EAP,WPRO,Upper Middle Income,Middle Income,East Asia & Pacific

In [236]:
merged["conflict_present"] = merged["conflict_present"].fillna(0)

In [237]:
merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 2294 entries, 0 to 2293
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   index                              2294 non-null   int64
 1   year                               2294 non-null   int64
 2   country                            2294 non-null   str
 3   Christianity                       2294 non-null   int64
 4   Judaism                            2294 non-null   int64
 5   Islam                              2294 non-null   int64
 6   Buddhism                           2294 non-null   int64
 7   Hindu                              2294 non-null   int64
 8   Shinto                             2294 non-null   int64
 9   Confus_Tao                         2294 non-null   int64
 10  code                               1030 non-null   str
 11  gdp                                1030 non-null   float64
 12  un_region                          618 non-null    str
 13  hdi                                618 non-null    float64
 14  conflict_present                   2294 non-null   float64
 15  iso_code                           618 non-null    str
 16  un_sub_region                      618 non-null    str
 17  sdg_region                         618 non-null    str
 18  development_regions                618 non-null    str
 19  unicef_region                      612 non-null    str
 20  unicef_subregions                  612 non-null    str
 21  who_region                         618 non-null    str
 22  world_bank_income_groups           618 non-null    str
 23  world_bank_income_groups_combined  618 non-null    str
 24  world_bank_regions                 618 non-null    str
dtypes: float64(3), int64(9), str(13)
memory usage: 448.2 KB

In [238]:
merged = merged.drop(merged.columns[[15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], axis=1)

In [239]:
merged = merged[(merged["year"] >= 1990)]

In [240]:
merged

,index,year,country,Christianity,Judaism,Islam,Buddhism,Hindu,Shinto,Confus_Tao,code,gdp,un_region,hdi,conflict_present
9,9,1990,United States,214425162,5508504,2294757,1575481,323352,59724,106818,USA,5.963144e+12,Northern America,0.875,0.0
10,10,1995,United States,215593975,5259463,2425377,1608346,574269,57972,62455,USA,7.639749e+12,NaN,NaN,0.0
11,11,2000,United States,219818305,5010424,2555997,2449569,825186,56220,18093,USA,1.025095e+13,Northern America,0.894,0.0
12,12,2005,United States,226464805,5536622,2685374,3682694,1311442,60560,90593,USA,1.303920e+13,NaN,NaN,0.0
13,13,2010,United States,233111307,5942248,2814750,3410236,1797698,156375,95752,USA,1.504896e+13,Northern America,0.916,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2303,1990,Samoa,159500,0,37,15,0,0,0,WSM,1.257663e+08,Oceania,0.672,0.0
2290,2304,1995,Samoa,161677,0,43,16,0,0,0,WSM,2.248657e+08,NaN,NaN,0.0
2291,2305,2000,Samoa,174600,0,50,18,0,0,0,WSM,2.588561e+08,Oceania,0.672,0.0
2292,2306,2005,Samoa,177510,0,58,18,0,0,0,WSM,4.768018e+08,NaN,NaN,0.0
2293,2307,2010,Samoa,180140,0,61,19,0,0,0,WSM,6.802609e+08,Oceania,0.704,0.0

In [241]:
display(merged.sort_values(by="country"))

,index,year,country,Christianity,Judaism,Islam,Buddhism,Hindu,Shinto,Confus_Tao,code,gdp,un_region,hdi,conflict_present
1899,1900,1990,Afghanistan,7000,130,15295070,4169,75000,0,0,AFG,0.000000e+00,Asia,0.284,1.0
1900,1901,1995,Afghanistan,6609,66,19026255,4357,46133,0,0,AFG,0.000000e+00,NaN,NaN,1.0
1901,1902,2000,Afghanistan,6219,0,22162133,4544,47000,0,0,AFG,3.521418e+09,Asia,0.340,1.0
1902,1903,2005,Afghanistan,24955,0,25497000,4012,8250,0,0,AFG,6.203257e+09,NaN,NaN,1.0
1903,1904,2010,Afghanistan,7287,0,26880000,2500,8000,0,0,AFG,1.585667e+10,Asia,0.449,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1498,1499,2010,Zimbabwe,9961179,11326,130448,182,18005,0,0,ZWE,1.204775e+10,Africa,0.481,0.0
1497,1498,2005,Zimbabwe,9865000,11432,72150,184,17939,0,0,ZWE,5.758250e+09,NaN,NaN,0.0
1496,1497,2000,Zimbabwe,7563983,10864,84200,175,17270,0,0,ZWE,6.693250e+09,Africa,0.426,0.0
1495,1496,1995,Zimbabwe,8271850,10132,82767,437,15385,0,0,ZWE,7.115000e+09,NaN,NaN,0.0
1494,1495,1990,Zimbabwe,6548714,9400,80000,700,13500,0,0,ZWE,8.788302e+09,Africa,0.479,0.0

In [242]:
region_to_country = merged.dropna(subset=["country"]).set_index("un_region")["country"]

In [243]:
merged["un_region"] = merged["un_region"].fillna(
    merged.groupby("country")["un_region"].transform("first")
)

In [244]:
merged

,index,year,country,Christianity,Judaism,Islam,Buddhism,Hindu,Shinto,Confus_Tao,code,gdp,un_region,hdi,conflict_present
9,9,1990,United States,214425162,5508504,2294757,1575481,323352,59724,106818,USA,5.963144e+12,Northern America,0.875,0.0
10,10,1995,United States,215593975,5259463,2425377,1608346,574269,57972,62455,USA,7.639749e+12,Northern America,NaN,0.0
11,11,2000,United States,219818305,5010424,2555997,2449569,825186,56220,18093,USA,1.025095e+13,Northern America,0.894,0.0
12,12,2005,United States,226464805,5536622,2685374,3682694,1311442,60560,90593,USA,1.303920e+13,Northern America,NaN,0.0
13,13,2010,United States,233111307,5942248,2814750,3410236,1797698,156375,95752,USA,1.504896e+13,Northern America,0.916,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,2303,1990,Samoa,159500,0,37,15,0,0,0,WSM,1.257663e+08,Oceania,0.672,0.0
2290,2304,1995,Samoa,161677,0,43,16,0,0,0,WSM,2.248657e+08,Oceania,NaN,0.0
2291,2305,2000,Samoa,174600,0,50,18,0,0,0,WSM,2.588561e+08,Oceania,0.672,0.0
2292,2306,2005,Samoa,177510,0,58,18,0,0,0,WSM,4.768018e+08,Oceania,NaN,0.0
2293,2307,2010,Samoa,180140,0,61,19,0,0,0,WSM,6.802609e+08,Oceania,0.704,0.0

In [245]:
merged["hdi"] = merged["hdi"].fillna(0)

In [246]:
merged.set_index("country").reset_index()

,country,index,year,Christianity,Judaism,Islam,Buddhism,Hindu,Shinto,Confus_Tao,code,gdp,un_region,hdi,conflict_present
0,United States,9,1990,214425162,5508504,2294757,1575481,323352,59724,106818,USA,5.963144e+12,Northern America,0.875,0.0
1,United States,10,1995,215593975,5259463,2425377,1608346,574269,57972,62455,USA,7.639749e+12,Northern America,0.000,0.0
2,United States,11,2000,219818305,5010424,2555997,2449569,825186,56220,18093,USA,1.025095e+13,Northern America,0.894,0.0
3,United States,12,2005,226464805,5536622,2685374,3682694,1311442,60560,90593,USA,1.303920e+13,Northern America,0.000,0.0
4,United States,13,2010,233111307,5942248,2814750,3410236,1797698,156375,95752,USA,1.504896e+13,Northern America,0.916,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,Samoa,2303,1990,159500,0,37,15,0,0,0,WSM,1.257663e+08,Oceania,0.672,0.0
1041,Samoa,2304,1995,161677,0,43,16,0,0,0,WSM,2.248657e+08,Oceania,0.000,0.0
1042,Samoa,2305,2000,174600,0,50,18,0,0,0,WSM,2.588561e+08,Oceania,0.672,0.0
1043,Samoa,2306,2005,177510,0,58,18,0,0,0,WSM,4.768018e+08,Oceania,0.000,0.0
1044,Samoa,2307,2010,180140,0,61,19,0,0,0,WSM,6.802609e+08,Oceania,0.704,0.0

In [247]:
merged = merged.drop(['index'], axis=1)
merged.drop_duplicates(inplace=True)

In [248]:
merged

,year,country,Christianity,Judaism,Islam,Buddhism,Hindu,Shinto,Confus_Tao,code,gdp,un_region,hdi,conflict_present
9,1990,United States,214425162,5508504,2294757,1575481,323352,59724,106818,USA,5.963144e+12,Northern America,0.875,0.0
10,1995,United States,215593975,5259463,2425377,1608346,574269,57972,62455,USA,7.639749e+12,Northern America,0.000,0.0
11,2000,United States,219818305,5010424,2555997,2449569,825186,56220,18093,USA,1.025095e+13,Northern America,0.894,0.0
12,2005,United States,226464805,5536622,2685374,3682694,1311442,60560,90593,USA,1.303920e+13,Northern America,0.000,0.0
13,2010,United States,233111307,5942248,2814750,3410236,1797698,156375,95752,USA,1.504896e+13,Northern America,0.916,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,1990,Samoa,159500,0,37,15,0,0,0,WSM,1.257663e+08,Oceania,0.672,0.0
2290,1995,Samoa,161677,0,43,16,0,0,0,WSM,2.248657e+08,Oceania,0.000,0.0
2291,2000,Samoa,174600,0,50,18,0,0,0,WSM,2.588561e+08,Oceania,0.672,0.0
2292,2005,Samoa,177510,0,58,18,0,0,0,WSM,4.768018e+08,Oceania,0.000,0.0
2293,2010,Samoa,180140,0,61,19,0,0,0,WSM,6.802609e+08,Oceania,0.704,0.0

In [249]:
#Load the updated HDI dataset containing yearly HDI values and dropping the old hdi column to prevent duplicated before merging the datasets
#Then we merged the updated HDI dataset with the main dataset using country and year as the keys ensuring that each country–year observation receives the correct HDI value.
hdi_new = pd.read_csv("hdi_long_final.csv")
merged = merged.drop(columns=["hdi"], errors="ignore")
merged = merged.merge(hdi_new,on=["country","year"],how="left")

#Check the number of null values and identify which countries contain missing HDI values to understand where data gaps exist in the HDI dataset
#Check whether the region classifications from the original dataset and the HDI dataset are identical across all observations.
#Count how many rows contain different region classifications between the two datasets.
#Examine the rows with missing HDI values to determine whether region mismatches occur due to missing HDI data.

merged["hdi"].isna().sum()
merged[merged["hdi"].isna()].groupby("country").size()
(merged["un_region_x"] == merged["un_region_y"]).all()
(merged["un_region_x"] != merged["un_region_y"]).sum()
merged[merged["hdi"].isna()][["country","year","un_region_x","un_region_y"]].head()

                country  year                      un_region_x un_region_y
35  Trinidad And Tobago  1990  Latin America and the Caribbean         NaN
36  Trinidad And Tobago  1995  Latin America and the Caribbean         NaN
37  Trinidad And Tobago  2000  Latin America and the Caribbean         NaN
38  Trinidad And Tobago  2005  Latin America and the Caribbean         NaN
39  Trinidad And Tobago  2010  Latin America and the Caribbean         NaN

In [250]:
#Remove the region column originating from the HDI dataset to avoid duplicate region variables.
#Rename the remaining region column for clarity and consistency within the dataset.

merged = merged.drop(columns=["un_region_y"])
merged = merged.rename(columns={"un_region_x": "un_region"})

In [251]:
#Standardised column names so they all follow the same format 
merged.columns = (merged.columns.str.strip().str.lower())

In [253]:
display(merged)

,year,country,christianity,judaism,islam,buddhism,hindu,shinto,confus_tao,code,gdp,un_region,conflict_present,hdi
0,1990,United States,214425162,5508504,2294757,1575481,323352,59724,106818,USA,5.963144e+12,Northern America,0.0,0.88
1,1995,United States,215593975,5259463,2425377,1608346,574269,57972,62455,USA,7.639749e+12,Northern America,0.0,0.89
2,2000,United States,219818305,5010424,2555997,2449569,825186,56220,18093,USA,1.025095e+13,Northern America,0.0,0.89
3,2005,United States,226464805,5536622,2685374,3682694,1311442,60560,90593,USA,1.303920e+13,Northern America,0.0,0.91
4,2010,United States,233111307,5942248,2814750,3410236,1797698,156375,95752,USA,1.504896e+13,Northern America,0.0,0.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,1990,Samoa,159500,0,37,15,0,0,0,WSM,1.257663e+08,Oceania,0.0,0.66
918,1995,Samoa,161677,0,43,16,0,0,0,WSM,2.248657e+08,Oceania,0.0,0.66
919,2000,Samoa,174600,0,50,18,0,0,0,WSM,2.588561e+08,Oceania,0.0,0.67
920,2005,Samoa,177510,0,58,18,0,0,0,WSM,4.768018e+08,Oceania,0.0,0.69
921,2010,Samoa,180140,0,61,19,0,0,0,WSM,6.802609e+08,Oceania,0.0,0.70

In [254]:
merged[merged["hdi"].isna()][["country","year","un_region"]].head()

                country  year                        un_region
35  Trinidad And Tobago  1990  Latin America and the Caribbean
36  Trinidad And Tobago  1995  Latin America and the Caribbean
37  Trinidad And Tobago  2000  Latin America and the Caribbean
38  Trinidad And Tobago  2005  Latin America and the Caribbean
39  Trinidad And Tobago  2010  Latin America and the Caribbean

In [255]:
merged[merged.duplicated(['country','year'], keep=False)]

,year,country,christianity,judaism,islam,buddhism,hindu,shinto,confus_tao,code,gdp,un_region,conflict_present,hdi
233,1990,Germany,62557600,47000,2850000,75000,45000,0,0,DEU,1.778162e+12,Europe,0.0,0.83
238,1990,Germany,57550000,15580,1490000,0,0,0,0,DEU,1.778162e+12,Europe,0.0,0.83
694,1990,Yemen,0,0,8560000,0,0,0,0,YEM,1.264382e+10,Asia,0.0,0.36
695,1990,Yemen,0,0,11225000,0,0,0,0,YEM,1.264382e+10,Asia,0.0,0.36
700,1990,Yemen,0,0,2333000,0,0,0,0,YEM,1.264382e+10,Asia,0.0,0.36

In [256]:
merged.groupby(['country','year']).size().sort_values(ascending=False)
merged = merged.drop_duplicates(subset=['country', 'year'])

In [257]:
merged.groupby(['country','year']).size().sort_values(ascending=False)

country      year
Afghanistan  1990    1
Norway       2010    1
Oman         1995    1
             2000    1
             2005    1
                    ..
Germany      1990    1
             1995    1
             2000    1
             2005    1
Zimbabwe     2010    1
Length: 919, dtype: int64

In [266]:
pop = pd.read_csv("pop_dataset.csv")

In [267]:
for c in sorted(merged["country"].unique()):
    print(c)

Afghanistan
Albania
Algeria
Andorra
Angola
Antigua And Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia (Plurinational State Of)
Bosnia And Herzegovina
Botswana
Brazil
Brunei Darussalam
Bulgaria
Burkina Faso
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo
Costa Rica
Croatia
Cuba
Cyprus
Czechia
Côte D'Ivoire
Democratic People'S Republic Of Korea
Democratic Republic Of The Congo
Denmark
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Hungary
Iceland
India
Indonesia
Iran (Islamic Republic Of)
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Kuwait
Kyrgyzstan
Lao People'S Democratic Republic
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia (Federated States Of)
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nauru
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Republic Of Korea
Republic Of Moldova
Romania
Russian Federation
Rwanda
Saint Kitts And Nevis
Saint Lucia
Saint Vincent And The Grenadines
Samoa
San Marino
Sao Tome And Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
Spain
Sri Lanka
Sudan
Suriname
Swaziland
Sweden
Switzerland
Syrian Arab Republic
Tajikistan
Thailand
The Former Yugoslav Republic Of Macedonia
Timor-Leste
Togo
Tonga
Trinidad And Tobago
Tunisia
Turkey
Turkmenistan
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Kingdom
United Republic Of Tanzania
United States
Uruguay
Uzbekistan
Vanuatu
Venezuela (Bolivarian Republic Of)
Viet Nam
Yemen
Zambia
Zimbabwe

In [268]:
pop = pop[pop["country"].isin(merged["country"])]

In [269]:
merged = merged.merge(pop, on=["code", "year"])

In [276]:
merged = merged.drop(columns=["country_y"])
merged = merged.rename(columns={"country_x": "country"})

merged

,year,country,christianity,judaism,islam,buddhism,hindu,shinto,confus_tao,code,gdp,un_region,conflict_present,hdi,population
0,1990,United States,214425162,5508504,2294757,1575481,323352,59724,106818,USA,5.963144e+12,Northern America,0.0,0.88,249623000.0
1,1995,United States,215593975,5259463,2425377,1608346,574269,57972,62455,USA,7.639749e+12,Northern America,0.0,0.89,266278000.0
2,2000,United States,219818305,5010424,2555997,2449569,825186,56220,18093,USA,1.025095e+13,Northern America,0.0,0.89,282162411.0
3,2005,United States,226464805,5536622,2685374,3682694,1311442,60560,90593,USA,1.303920e+13,Northern America,0.0,0.91,295516599.0
4,2010,United States,233111307,5942248,2814750,3410236,1797698,156375,95752,USA,1.504896e+13,Northern America,0.0,0.92,309378227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,1990,Samoa,159500,0,37,15,0,0,0,WSM,1.257663e+08,Oceania,0.0,0.66,169042.0
775,1995,Samoa,161677,0,43,16,0,0,0,WSM,2.248657e+08,Oceania,0.0,0.66,174571.0
776,2000,Samoa,174600,0,50,18,0,0,0,WSM,2.588561e+08,Oceania,0.0,0.67,181685.0
777,2005,Samoa,177510,0,58,18,0,0,0,WSM,4.768018e+08,Oceania,0.0,0.69,186978.0
778,2010,Samoa,180140,0,61,19,0,0,0,WSM,6.802609e+08,Oceania,0.0,0.70,193023.0

In [277]:
merged.to_csv("final_dataset.csv", index=False)

In [278]:
merged["population"].isnull().sum()

np.int64(0)

KeyError: 'country'