In [68]:
import pandas as pd

df = pd.read_csv("country_pop.csv", sep=",", skiprows=3)
df.columns

df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(r"[^\w\s]", "", regex=True)
        .str.replace(" ", "_"))

df = df.rename(columns={"country_name":"country", "country_code": "code"})
df

,country,code,indicator_name,indicator_code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,unnamed_70
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,...,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,984846.0,1011421.0,1036950.0,1062737.0,1090270.0,1120168.0,...,1791019.0,1797086.0,1788891.0,1790151.0,1786079.0,1768096.0,1682668.0,1594353.0,NaN,NaN
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5532301.0,5655232.0,5782221.0,5911135.0,6048006.0,6195593.0,...,33090921.0,34085182.0,35111408.0,36134863.0,37140230.0,38222876.0,39390799.0,40583164.0,NaN,NaN
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,16440172.0,16908035.0,17418522.0,17954564.0,18511361.0,19089380.0,...,57635162.0,58613001.0,59587885.0,60562381.0,61502603.0,62378410.0,63212384.0,64007187.0,NaN,NaN
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3153729.0,3254086.0,3358099.0,3465907.0,3577017.0,3692086.0,...,17441320.0,17973569.0,18513839.0,19059395.0,19603607.0,20152938.0,20723965.0,21314956.0,NaN,NaN
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3809389.0,3930401.0,4055959.0,4185877.0,4320006.0,4458462.0,...,14812482.0,15034452.0,15271368.0,15526888.0,15797210.0,16069056.0,16340822.0,16634373.0,NaN,NaN

In [70]:
pop_long = (
    df.melt(
        id_vars=["country", "code"],
        var_name="year",
        value_name="population"))


pop_long["year"] = pd.to_numeric(pop_long["year"], errors="coerce")
pop_long = pop_long.dropna(subset=["year", "population"])

pop_long = pop_long[(pop_long["year"] >= 1990)]
pop_long["year"] = pop_long["year"].astype(int)
pop_long

                           country code  year   population
8512                         Aruba  ABW  1990      62753.0
8513   Africa Eastern and Southern  AFE  1990  311748681.0
8514                   Afghanistan  AFG  1990   12045660.0
8515    Africa Western and Central  AFW  1990  209566031.0
8516                        Angola  AGO  1990   11626360.0
...                            ...  ...   ...          ...
17817                       Kosovo  XKX  2024    1594353.0
17818                  Yemen, Rep.  YEM  2024   40583164.0
17819                 South Africa  ZAF  2024   64007187.0
17820                       Zambia  ZMB  2024   21314956.0
17821                     Zimbabwe  ZWE  2024   16634373.0

[9275 rows x 4 columns]

In [71]:
pop_long.to_csv("pop_dataset.csv", index=False)

In [52]:
for c in sorted(pop_long["country"].unique()):
    print(c)

Afghanistan
Africa Eastern and Southern
Africa Western and Central
Albania
Algeria
American Samoa
Andorra
Angola
Antigua and Barbuda
Arab World
Argentina
Armenia
Aruba
Australia
Austria
Azerbaijan
Bahamas, The
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bermuda
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
British Virgin Islands
Brunei Darussalam
Bulgaria
Burkina Faso
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Caribbean small states
Cayman Islands
Central African Republic
Central Europe and the Baltics
Chad
Channel Islands
Chile
China
Colombia
Comoros
Congo, Dem. Rep.
Congo, Rep.
Costa Rica
Cote d'Ivoire
Croatia
Cuba
Curacao
Cyprus
Czechia
Denmark
Djibouti
Dominica
Dominican Republic
Early-demographic dividend
East Asia & Pacific
East Asia & Pacific (IDA & IBRD countries)
East Asia & Pacific (excluding high income)
Ecuador
Egypt, Arab Rep.
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Euro area
Europe & Central Asia
Europe & Central Asia (IDA & IBRD countries)
Europe & Central Asia (excluding high income)
European Union
Faroe Islands
Fiji
Finland
Fragile and conflict affected situations
France
French Polynesia
Gabon
Gambia, The
Georgia
Germany
Ghana
Gibraltar
Greece
Greenland
Grenada
Guam
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Heavily indebted poor countries (HIPC)
High income
Honduras
Hong Kong SAR, China
Hungary
IBRD only
IDA & IBRD total
IDA blend
IDA only
IDA total
Iceland
India
Indonesia
Iran, Islamic Rep.
Iraq
Ireland
Isle of Man
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, Dem. People's Rep.
Korea, Rep.
Kosovo
Kuwait
Kyrgyz Republic
Lao PDR
Late-demographic dividend
Latin America & Caribbean
Latin America & Caribbean (excluding high income)
Latin America & the Caribbean (IDA & IBRD countries)
Latvia
Least developed countries: UN classification
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Low & middle income
Low income
Lower middle income
Luxembourg
Macao SAR, China
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia, Fed. Sts.
Middle East, North Africa, Afghanistan & Pakistan
Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)
Middle East, North Africa, Afghanistan & Pakistan (excluding high income)
Middle income
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nauru
Nepal
Netherlands
New Caledonia
New Zealand
Nicaragua
Niger
Nigeria
North America
North Macedonia
Northern Mariana Islands
Norway
OECD members
Oman
Other small states
Pacific island small states
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Post-demographic dividend
Pre-demographic dividend
Puerto Rico (US)
Qatar
Romania
Russian Federation
Rwanda
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Sint Maarten (Dutch part)
Slovak Republic
Slovenia
Small states
Solomon Islands
Somalia, Fed. Rep.
South Africa
South Asia
South Asia (IDA & IBRD)
South Sudan
Spain
Sri Lanka
St. Kitts and Nevis
St. Lucia
St. Martin (French part)
St. Vincent and the Grenadines
Sub-Saharan Africa
Sub-Saharan Africa (IDA & IBRD countries)
Sub-Saharan Africa (excluding high income)
Sudan
Suriname
Sweden
Switzerland
Syrian Arab Republic
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Tonga
Trinidad and Tobago
Tunisia
Turkiye
Turkmenistan
Turks and Caicos Islands
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Upper middle income
Uruguay
Uzbekistan
Vanuatu
Venezuela, RB
Viet Nam
Virgin Islands (U.S.)
West Bank and Gaza
World
Yemen, Rep.
Zambia
Zimbabwe

In [53]:
pop_long

                           country  year   population
8778                         Aruba  1990      62753.0
8779   Africa Eastern and Southern  1990  311748681.0
8780                   Afghanistan  1990   12045660.0
8781    Africa Western and Central  1990  209566031.0
8782                        Angola  1990   11626360.0
...                            ...   ...          ...
18083                       Kosovo  2024    1594353.0
18084                  Yemen, Rep.  2024   40583164.0
18085                 South Africa  2024   64007187.0
18086                       Zambia  2024   21314956.0
18087                     Zimbabwe  2024   16634373.0

[9275 rows x 3 columns]