In [144]:
import pandas as pd
import numpy as np

# Load the dataset Religions
src = r"C:\Users\Utilisateur\Desktop\IRONHACK_DA\COURSES\week-4\first_project\data\raw/ThrowbackDataThursday 201912 - Religion.csv"
df = pd.read_csv(src)

# Drop duplicates and na, adding a column name for index
df.drop_duplicates(inplace=True)
df.dropna()

# Filter from 1960 to 2022
# df = df[(df.Year >=1960) & (df.Year <=2022)]

# Keep state, year, total per religion

df = df[[col for col in df.columns if col.endswith("Total (Population)") or col == "Year" or col == "StateNme" ]]

# Rename columns
df.columns = [col.replace("- Total (Population)","").replace("StateNme","Country").strip() for col in df.columns]
df.columns

# Group Chinese main phisolohpies
df["Confus_Tao"] = df["Taoism"] + df["Confucianism"]

# Remove rows with total percentages over 1
# df = df[df["Total Religious _pct"] <= 1]

df.columns

df = df[["Year", "Country", "Christianity", "Judaism", "Islam", "Buddhism", "Hindu", "Shinto", "Confus_Tao"]]
#df

# df.to_csv(r"C:\Users\Utilisateur\Desktop\IRONHACK_DA\COURSES\week-4\first_project\data\raw/check.csv")

In [145]:
# Load the dataset of country referencing
src1 = r'C:\Users\Utilisateur\Desktop\IRONHACK_DA\COURSES\week-4\first_project\data\raw\JME_Regional-Classifications.csv'
ref_country = pd.read_csv(src1, sep = ';')

# Get the unique values of country
countries = pd.DataFrame(df.Country.unique())
countries.columns = ["Country"]

# Get the countries that do no match with the official list
missing_countries = countries[~countries['Country'].isin(ref_country['Country'])]

In [148]:
# Replace the countries names accordingly

country_mapping = {
    "Antigua & Barbuda": "Antigua and Barbuda",
    "Bolivia": "Bolivia (Plurinational State of)",
    "Brunei": "Brunei Darussalam",
    "Cape Verde": "Cabo Verde",
    "Czech Republic": "Czechia",
    "Czechoslovakia": "Slovakia",
    "East Timor": "Timor-Leste",
    "Federated States of Micronesia": "Micronesia (Federated States of)",
    "German Federal Republic": "Germany",
    "Iran": "Iran (Islamic Republic of)",
    "Ivory Coast": "Côte d'Ivoire",
    "Laos": "Lao People's Democratic Republic",
    "Macedonia": "The former Yugoslav Republic of Macedonia",
    "Moldova": "Republic of Moldova",
    "North Korea": "Democratic People's Republic of Korea",
    "Russia": "Russian Federation",
    "South Korea": "Republic of Korea",
    "St. Kitts and Nevis": "Saint Kitts and Nevis",
    "St. Lucia": "Saint Lucia",
    "St. Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Syria": "Syrian Arab Republic",
    "Tanzania": "United Republic of Tanzania",
    "United States of America": "United States",
    "Venezuela": "Venezuela (Bolivarian Republic of)",
    "Vietnam": "Viet Nam",
    "Yemen Arab Republic": "Yemen",
    "Yemen People's Republic": "Yemen",
    "Yugoslavia": "Serbia"
}

df['Country'] = df['Country'].replace(country_mapping)

In [149]:
# Remove the countries with no match
df = df[~ df["Country"].isin(["Kosovo", "Taiwan"])].reset_index()

In [150]:
# Export to csv
df = df.reset_index(drop=True) 
df.to_csv(r"C:\Users\Utilisateur\Desktop\IRONHACK_DA\COURSES\week-4\first_project\data\clean\clean_religions.csv", index = False)

List of the columns of the dataset clean_religions (updated on 10-03-2026)
index 
'Year
Country
Christianity
Judaism
Islam
Buddhism
Hindu
Shinto
Confus_Tao

In [151]:
# Load the dataset of country referencing
src2 = r'C:\Users\Utilisateur\Desktop\IRONHACK_DA\COURSES\week-4\first_project\data\raw\Conflict_Site.csv'
conflict_countries = pd.read_csv(src2, sep = ';')

# Rename column (use a dict! when only one values otherwise list comprehension)
conflict_countries.rename(columns={"Conflict territory": "Country"}, inplace=True)

conflict_countries = conflict_countries[["Year", "Country"]]
conflict_countries

      Year                    Country
0     1946                    Bolivia
1     1952                    Bolivia
2     1967                    Bolivia
3     1946  French colony of Cambodia
4     1947  French colony of Cambodia
...    ...                        ...
1837  2005                   Thailand
1838  2003                   Thailand
1839  2004                   Thailand
1840  2004                    Nigeria
1841  2004                    Nigeria

[1842 rows x 2 columns]

In [152]:
# Remove white space after comma
conflict_countries["Country"] = conflict_countries["Country"].str.replace(", ", ",")

In [153]:
# The country value becomes a list when there is a comma
conflict_countries["Country"] = conflict_countries["Country"].str.split(",")

In [154]:
# Then you can create a line for each country
conflict_countries = conflict_countries.explode("Country").reset_index(drop=True)

In [155]:
# Get the unique values of country
countries2 = pd.DataFrame(conflict_countries.Country.unique())
countries2.columns = ["Country"]

# Get the countries that do no match with the official list
missing_countries2 = countries2[~countries2['Country'].isin(ref_country['Country'])]

# Map the discrepancies betwenn the un list and our dataset
country_conflict_mapping = {
    "Bolivia": "Bolivia (Plurinational State of)",
    "French colony of Cambodia": "Cambodia",
    "Dutch colony of Indonesia": "Indonesia",
    "Iran": "Iran (Islamic Republic of)",
    "Pre Israel": "State of Palestine",
    "French colony of Laos": "Lao People's Democratic Republic",
    "Soviet Union": "Russian Federation",
    "French colony of Siam": "Thailand",
    "French colony of Vietnam": "Viet Nam",
    "Hyderabad": "India",
    "French colony of Madagascar": "Madagascar",
    "Burma": "Myanmar",
    "British colony of Malaysia": "Malaysia",
    "South Korea": "Republic of Korea",
    "Yemen (North)": "Yemen",
    "North Korea": "Democratic People's Republic of Korea",
    "South Vietnam": "Viet Nam",
    "North Vietnam": "Viet Nam",
    "US territory of Puerto Rico": "United States",
    "British colony of Kenya": "Kenya",
    "French colony of Morocco": "Morocco",
    "French colony of Tunisia": "Tunisia",
    "French colony of Algeria": "Algeria",
    "British colony of Cyprus": "Cyprus",
    "French colony of Cameroon": "Cameroon",
    "Laos": "Lao People's Democratic Republic",
    "Portuguese colony of Angola": "Angola",
    "Congo/Zaire": "Democratic Republic of the Congo",
    "British colony of Brunei": "Brunei Darussalam",
    "Venezuela": "Venezuela (Bolivarian Republic of)",
    "Portuguese colony of Guinea": "Guinea-Bissau",
    "Portuguese colony of Mozambique": "Mozambique",
    "British colony of Yemen": "Yemen",
    "Syria": "Syrian Arab Republic",
    "Rhodesia": "Zimbabwe",
    "North Yemen": "Yemen",
    "Vietnam": "Viet Nam",
    "British Territory of Falkland": "United Kingdom",
    "Burkino Faso": "Burkina Faso",
    "Surinam": "Suriname",
    "Yemen (South)": "Yemen",
    "Yugoslavia": "Serbia",
    "Moldova": "Republic of Moldova",
    "Russia": "Russian Federation",
    "Congo-Brazzaville": "Congo",
    "Macedonia": "The former Yugoslav Republic of Macedonia",
    "USA": "United States",
    "Ivory Coast": "Côte d'Ivoire"
}

# Update
conflict_countries['Country'] = conflict_countries['Country'].replace(country_conflict_mapping)

In [156]:
# Drop duplicates and na 
conflict_countries.drop_duplicates(inplace=True)
conflict_countries.dropna()

      Year                           Country
0     1946  Bolivia (Plurinational State of)
1     1952  Bolivia (Plurinational State of)
2     1967  Bolivia (Plurinational State of)
3     1946                          Cambodia
4     1947                          Cambodia
...    ...                               ...
1910  2003                              Iraq
1926  2005                          Thailand
1927  2003                          Thailand
1928  2004                          Thailand
1929  2004                           Nigeria

[1418 rows x 2 columns]

In [157]:
# Export to csv
conflict_countries = conflict_countries.reset_index(drop=True) 
conflict_countries.to_csv(r"C:\Users\Utilisateur\Desktop\IRONHACK_DA\COURSES\week-4\first_project\data\clean\conflict_countries.csv", index = False)

The mapping aligns historical or colonial country names to modern standardized country names in a consistent way. Colonies such as “French colony of Cambodia” are mapped to their current independent states like Cambodia. Historical entities that no longer exist, such as the Soviet Union and Yugoslavia, are mapped to their primary successor states—Russian Federation and Serbia respectively—while acknowledging that more detailed analyses could split them into multiple modern countries. “Pre Israel” is mapped to State of Palestine, reflecting the closest geopolitical entity. This approach ensures that all historical or obsolete names correspond to entries present in the modern country list, facilitating consistent analysis and visualization in historical conflict datasets.