In [44]:
import pandas as pd
import numpy as np
import seaborn as sns

final = r"C:\Users\Utilisateur\Desktop\IRONHACK_DA\COURSES\week-4\first_project\data\clean\final_dataset.csv"
df = pd.read_csv(final)
df = df.drop(['Unnamed: 0'], axis=1)
df.drop_duplicates(inplace=True)

In [45]:
df

,year,country,Christianity,Judaism,Islam,Buddhism,Hindu,Shinto,Confus_Tao,code,gdp,un_region,hdi,conflict_present
0,1990,United States,214425162,5508504,2294757,1575481,323352,59724,106818,USA,5.963144e+12,Northern America,0.875,0.0
1,1995,United States,215593975,5259463,2425377,1608346,574269,57972,62455,USA,7.639749e+12,Northern America,0.000,0.0
2,2000,United States,219818305,5010424,2555997,2449569,825186,56220,18093,USA,1.025095e+13,Northern America,0.894,0.0
3,2005,United States,226464805,5536622,2685374,3682694,1311442,60560,90593,USA,1.303920e+13,Northern America,0.000,0.0
4,2010,United States,233111307,5942248,2814750,3410236,1797698,156375,95752,USA,1.504896e+13,Northern America,0.916,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,1990,Samoa,159500,0,37,15,0,0,0,WSM,1.257663e+08,Oceania,0.672,0.0
918,1995,Samoa,161677,0,43,16,0,0,0,WSM,2.248657e+08,Oceania,0.000,0.0
919,2000,Samoa,174600,0,50,18,0,0,0,WSM,2.588561e+08,Oceania,0.672,0.0
920,2005,Samoa,177510,0,58,18,0,0,0,WSM,4.768018e+08,Oceania,0.000,0.0
921,2010,Samoa,180140,0,61,19,0,0,0,WSM,6.802609e+08,Oceania,0.704,0.0

In [47]:
# real long format
long_df = df.melt(id_vars=['year','country','gdp','un_region','hdi','conflict_present'], var_name ='religion', value_name = 'relig_pop')

In [48]:
# export
long_df.to_csv(r"C:\Users\Utilisateur\Desktop\IRONHACK_DA\COURSES\week-4\first_project\data\raw\long_df.csv")

In [49]:
long_df

,year,country,gdp,un_region,hdi,conflict_present,religion,relig_pop
0,1990,United States,5.963144e+12,Northern America,0.875,0.0,Christianity,214425162
1,1995,United States,7.639749e+12,Northern America,0.000,0.0,Christianity,215593975
2,2000,United States,1.025095e+13,Northern America,0.894,0.0,Christianity,219818305
3,2005,United States,1.303920e+13,Northern America,0.000,0.0,Christianity,226464805
4,2010,United States,1.504896e+13,Northern America,0.916,0.0,Christianity,233111307
...,...,...,...,...,...,...,...,...
7371,1990,Samoa,1.257663e+08,Oceania,0.672,0.0,code,WSM
7372,1995,Samoa,2.248657e+08,Oceania,0.000,0.0,code,WSM
7373,2000,Samoa,2.588561e+08,Oceania,0.672,0.0,code,WSM
7374,2005,Samoa,4.768018e+08,Oceania,0.000,0.0,code,WSM
7375,2010,Samoa,6.802609e+08,Oceania,0.704,0.0,code,WSM

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = long_df

# -----------------------------
# 1️⃣ Line plot : population totale par an et par région
# -----------------------------
pop_region_year = df.groupby(['year','un_region'])['relig_pop'].sum().reset_index()

plt.figure(figsize=(12,6))
sns.lineplot(data=pop_region_year, x='year', y='relig_pop', hue='un_region', marker='o')
plt.title("Population totale par année et par région")
plt.ylabel("Population totale")
plt.xlabel("Année")
plt.legend(title="Région")
plt.show()

# -----------------------------
# 2️⃣ Bar plots : moyenne de la population par religion et par région
# -----------------------------
# Moyenne par region et religion
mean_relig = df.groupby(['un_region','religion'])['relig_pop'].mean().reset_index()

# a) Graph empilé avec valeurs absolues
plt.figure(figsize=(12,6))
sns.barplot(data=mean_relig, x='un_region', y='relig_pop', hue='religion')
plt.title("Moyenne de population par religion et par région")
plt.ylabel("Population moyenne")
plt.xlabel("Région")
plt.legend(title="Religion")
plt.show()

# b) Graph empilé en pourcentage
# On calcule la proportion par region
mean_relig_pct = mean_relig.copy()
mean_relig_pct['proportion'] = mean_relig_pct.groupby('un_region')['relig_pop'].apply(lambda x: x / x.sum())

plt.figure(figsize=(12,6))
sns.barplot(data=mean_relig_pct, x='un_region', y='proportion', hue='religion')
plt.title("Répartition proportionnelle des religions par région")
plt.ylabel("Proportion")
plt.xlabel("Région")
plt.legend(title="Religion")
plt.show()

# -----------------------------
# 3️⃣ Heatmap : moyenne population par religion et par pays, filtrée par région
# -----------------------------
regions = df['un_region'].unique()

for region in regions:
    df_region = df[df['un_region'] == region]
    pivot = df_region.pivot_table(index='country', columns='religion', values='relig_pop', aggfunc='mean', fill_value=0)
    
    plt.figure(figsize=(12, max(4, len(pivot)*0.5)))
    sns.heatmap(pivot, annot=True, fmt=".0f", cmap="YlGnBu")
    plt.title(f"Moyenne population par religion pour les pays de {region}")
    plt.ylabel("Pays")
    plt.xlabel("Religion")
    plt.show()