In [170]:
import pandas as pd

df = pd.read_csv("gdp_raw_data_file.csv", skiprows=4)
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,...,9.780765e+11,1.020956e+12,1.018715e+12,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12,NaN,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,...,6.940513e+11,7.778403e+11,1.026996e+12,9.637847e+11,1.026651e+12,1.063649e+12,9.382384e+11,7.363850e+11,NaN,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.180769e+09,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10,NaN,NaN
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.684223e+10,2.160616e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,3.814488e+11,4.052607e+11,3.893300e+11,3.379747e+11,4.199863e+11,4.075960e+11,3.814407e+11,4.011450e+11,NaN,NaN
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,6.987397e+08,6.823597e+08,6.792797e+08,7.043397e+08,8.226397e+08,1.061200e+09,...,2.587360e+10,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,NaN,NaN
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.053528e+09,1.097207e+09,1.118172e+09,1.160104e+09,1.217759e+09,1.312105e+09,...,5.103566e+10,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10,NaN,NaN

In [171]:
years = [str(year) for year in range(1990, 2025)]
df = df.rename(columns={"Country Name": "country", "Country Code": "code"})
df = df[['country', 'code'] + years]
df['country'] = df['country'].str.strip()
df

,country,code,1990,1991,1992,1993,1994,1995,1996,1997,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,7.648045e+08,8.720670e+08,9.586592e+08,1.083240e+09,1.245810e+09,1.320670e+09,1.379888e+09,1.531844e+09,...,2.962907e+09,2.983637e+09,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09
1,Africa Eastern and Southern,AFE,2.563831e+11,2.769185e+11,2.411883e+11,2.399812e+11,2.434775e+11,2.733270e+11,2.734276e+11,2.882707e+11,...,9.100020e+11,8.318681e+11,9.780765e+11,1.020956e+12,1.018715e+12,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.913422e+10,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN
3,Africa Western and Central,AFW,1.242778e+11,1.307943e+11,1.254494e+11,1.305471e+11,1.353508e+11,2.078439e+11,2.635636e+11,2.764600e+11,...,7.780221e+11,7.000282e+11,6.940513e+11,7.778403e+11,1.026996e+12,9.637847e+11,1.026651e+12,1.063649e+12,9.382384e+11,7.363850e+11
4,Angola,AGO,1.122952e+10,1.060378e+10,8.307811e+09,5.768720e+09,4.438321e+09,5.538749e+09,7.526422e+09,7.648380e+09,...,1.025431e+11,5.987825e+10,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.295848e+09,6.682677e+09,7.180769e+09,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10
262,"Yemen, Rep.",YEM,1.264382e+10,1.466545e+10,1.795937e+10,2.173680e+10,2.801948e+10,1.279635e+10,6.496164e+09,6.838299e+09,...,4.244449e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,1.260481e+11,1.352037e+11,1.469562e+11,1.471947e+11,1.535127e+11,1.717359e+11,1.632349e+11,1.689781e+11,...,3.467098e+11,3.235855e+11,3.814488e+11,4.052607e+11,3.893300e+11,3.379747e+11,4.199863e+11,4.075960e+11,3.814407e+11,4.011450e+11
264,Zambia,ZMB,3.288382e+09,3.376807e+09,3.182811e+09,3.273505e+09,3.656806e+09,3.806983e+09,3.597221e+09,4.303288e+09,...,2.125122e+10,2.095841e+10,2.587360e+10,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10
265,Zimbabwe,ZWE,8.788302e+09,8.646000e+09,6.755000e+09,6.567250e+09,6.894250e+09,7.115000e+09,8.557500e+09,8.534000e+09,...,1.997325e+10,2.055925e+10,5.103566e+10,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10

In [172]:
df.dtypes

country     object
code        object
1990       float64
1991       float64
1992       float64
1993       float64
1994       float64
1995       float64
1996       float64
1997       float64
1998       float64
1999       float64
2000       float64
2001       float64
2002       float64
2003       float64
2004       float64
2005       float64
2006       float64
2007       float64
2008       float64
2009       float64
2010       float64
2011       float64
2012       float64
2013       float64
2014       float64
2015       float64
2016       float64
2017       float64
2018       float64
2019       float64
2020       float64
2021       float64
2022       float64
2023       float64
2024       float64
dtype: object

In [173]:
df[years].isna().sum()

1990    26
1991    25
1992    24
1993    23
1994    22
1995    19
1996    19
1997    17
1998    16
1999    16
2000    14
2001    13
2002     9
2003     9
2004     9
2005     9
2006     8
2007     8
2008     7
2009     5
2010     5
2011     4
2012     6
2013     6
2014     5
2015     6
2016     7
2017     7
2018     7
2019     7
2020     8
2021     8
2022     9
2023    15
2024    26
dtype: int64

In [184]:
df['country'] = df['country'].str.strip()
required_countries = [
    "Afghanistan","Albania","Algeria","Andorra","Angola","Anguilla","Antigua and Barbuda",
    "Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh",
    "Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia (Plurinational State of)",
    "Bosnia and Herzegovina","Botswana","Brazil","British Virgin Islands","Brunei Darussalam",
    "Bulgaria","Burkina Faso","Burundi","Cabo Verde","Cambodia","Cameroon","Canada",
    "Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo","Cook Islands",
    "Costa Rica","Côte d'Ivoire","Croatia","Cuba","Cyprus","Czechia","Democratic People's Republic of Korea",
    "Democratic Republic of the Congo","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador",
    "Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Ethiopia","Fiji","Finland",
    "France","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea",
    "Guinea-Bissau","Guyana","Haiti","Holy See","Honduras","Hungary","Iceland","India","Indonesia",
    "Iran (Islamic Republic of)","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan",
    "Kenya","Kiribati","Kuwait","Kyrgyzstan","Lao People's Democratic Republic","Latvia","Lebanon",
    "Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi",
    "Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico",
    "Micronesia (Federated States of)","Monaco","Mongolia","Montenegro","Montserrat","Morocco",
    "Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua",
    "Niger","Nigeria","Niue","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea",
    "Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Republic of Korea",
    "Republic of Moldova","Romania","Russian Federation","Rwanda","Saint Kitts and Nevis",
    "Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","Sao Tome and Principe",
    "Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia",
    "Solomon Islands","Somalia","South Africa","South Sudan","Spain","Sri Lanka","State of Palestine",
    "Sudan","Suriname","Swaziland","Sweden","Switzerland","Syrian Arab Republic","Tajikistan",
    "Thailand","The former Yugoslav Republic of Macedonia","Timor-Leste","Togo","Tokelau","Tonga",
    "Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Turks and Caicos Islands","Tuvalu",
    "Uganda","Ukraine","United Arab Emirates","United Kingdom","United Republic of Tanzania",
    "United States","Uruguay","Uzbekistan","Vanuatu","Venezuela (Bolivarian Republic of)","Viet Nam",
    "Yemen","Zambia","Zimbabwe"
]
name_map = {
    "Democratic People's Republic of Korea": "Korea, Dem. People's Rep.",
    "The former Yugoslav Republic of Macedonia": "North Macedonia",
    "State of Palestine": "Palestine, State of",
    "United Republic of Tanzania": "United Republic of Tanzania",
    "Bahamas, The": "Bahamas",
    "Cote d'Ivoire": "Côte d'Ivoire",
    "Egypt, Arab Rep.": "Egypt",
    "Gambia, The": "Gambia",
    "Iran, Islamic Rep.": "Iran (Islamic Republic of)",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Korea, Rep.": "Republic of Korea",
    "Lao PDR": "Lao People's Democratic Republic",
    "Micronesia, Fed. Sts.": "Micronesia (Federated States of)",
    "Moldova": "Republic of Moldova",
    "North Macedonia": "The former Yugoslav Republic of Macedonia",
    "Turkiye": "Turkey",
    "Venezuela, RB": "Venezuela (Bolivarian Republic of)",
    "Yemen, Rep.": "Yemen",
    "Somalia, Fed. Rep.": "Somalia",
    "Slovak Republic": "Slovakia",
    "Eswatini": "Swaziland",
    "Hong Kong SAR, China": "Hong Kong SAR, China",
    "Macao SAR, China": "Macao SAR, China",
    "West Bank and Gaza": "West Bank and Gaza",
    "Puerto Rico (US)": "Puerto Rico (US)",
    "Northern Mariana Islands": "Northern Mariana Islands",
    "Sint Maarten (Dutch part)": "Sint Maarten (Dutch part)",
    "St. Martin (French part)": "St. Martin (French part)",
    "Virgin Islands (U.S.)": "Virgin Islands (U.S.)",
    "Palestine, State of": "State of Palestine",
    "Congo, Dem. Rep.": "Democratic Republic of the Congo",
    "Congo, Rep.": "Congo",
    "St. Kitts and Nevis": "Saint Kitts and Nevis",
    "St. Lucia": "Saint Lucia",
    "St. Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Brunei Darussalam": "Brunei Darussalam"
}
df['country'] = df['country'].replace(name_map)
df_new = df[df['country'].isin(required_countries)].reset_index(drop=True)
df_new

,country,code,1990,1991,1992,1993,1994,1995,1996,1997,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.913422e+10,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN
1,Angola,AGO,1.122952e+10,1.060378e+10,8.307811e+09,5.768720e+09,4.438321e+09,5.538749e+09,7.526422e+09,7.648380e+09,...,1.025431e+11,5.987825e+10,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11
2,Albania,ALB,2.028554e+09,1.099559e+09,6.521750e+08,1.185315e+09,1.880951e+09,2.905093e+09,3.234486e+09,2.293666e+09,...,1.147017e+10,1.198867e+10,1.325827e+10,1.537951e+10,1.558511e+10,1.524146e+10,1.803199e+10,1.901725e+10,2.349124e+10,2.704643e+10
3,Andorra,AND,1.028990e+09,1.106891e+09,1.209992e+09,1.007090e+09,1.017544e+09,1.178745e+09,1.224024e+09,1.180646e+09,...,2.789883e+09,2.896612e+09,3.000160e+09,3.218419e+09,3.155150e+09,2.891002e+09,3.324648e+09,3.380612e+09,3.785066e+09,4.039842e+09
4,United Arab Emirates,ARE,5.070144e+10,5.155217e+10,5.423917e+10,5.562517e+10,5.930509e+10,6.574367e+10,7.357123e+10,7.883901e+10,...,3.819730e+11,3.817171e+11,4.033650e+11,4.405601e+11,4.339262e+11,3.571619e+11,4.224414e+11,5.114034e+11,5.226222e+11,5.523248e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,Samoa,WSM,1.257663e+08,1.255972e+08,1.323030e+08,1.331229e+08,2.210981e+08,2.248657e+08,2.499079e+08,2.854756e+08,...,8.241505e+08,8.439248e+08,8.848444e+08,8.784484e+08,9.129505e+08,8.688849e+08,8.597249e+08,8.895547e+08,1.044910e+09,1.175750e+09
188,Yemen,YEM,1.264382e+10,1.466545e+10,1.795937e+10,2.173680e+10,2.801948e+10,1.279635e+10,6.496164e+09,6.838299e+09,...,4.244449e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN,NaN,NaN,NaN
189,South Africa,ZAF,1.260481e+11,1.352037e+11,1.469562e+11,1.471947e+11,1.535127e+11,1.717359e+11,1.632349e+11,1.689781e+11,...,3.467098e+11,3.235855e+11,3.814488e+11,4.052607e+11,3.893300e+11,3.379747e+11,4.199863e+11,4.075960e+11,3.814407e+11,4.011450e+11
190,Zambia,ZMB,3.288382e+09,3.376807e+09,3.182811e+09,3.273505e+09,3.656806e+09,3.806983e+09,3.597221e+09,4.303288e+09,...,2.125122e+10,2.095841e+10,2.587360e+10,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10
191,Zimbabwe,ZWE,8.788302e+09,8.646000e+09,6.755000e+09,6.567250e+09,6.894250e+09,7.115000e+09,8.557500e+09,8.534000e+09,...,1.997325e+10,2.055925e+10,5.103566e+10,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10

In [185]:
missing_countries = [c for c in required_countries if c not in df_new['country'].unique()]
print("Countries in 202 list but missing in dataset:", missing_countries)
print("Number of rows in cleaned dataset:", len(df_new))

Countries in 202 list but missing in dataset: ['Anguilla', 'Bolivia (Plurinational State of)', 'Cook Islands', "Democratic People's Republic of Korea", 'Holy See', 'Montserrat', 'Niue', 'State of Palestine', 'Tokelau', 'United Republic of Tanzania']
Number of rows in cleaned dataset: 192

In [186]:
df_clean = df_new.fillna(0)
df_clean

,country,code,1990,1991,1992,1993,1994,1995,1996,1997,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,AFG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.913422e+10,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,0.000000e+00
1,Angola,AGO,1.122952e+10,1.060378e+10,8.307811e+09,5.768720e+09,4.438321e+09,5.538749e+09,7.526422e+09,7.648380e+09,...,1.025431e+11,5.987825e+10,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11
2,Albania,ALB,2.028554e+09,1.099559e+09,6.521750e+08,1.185315e+09,1.880951e+09,2.905093e+09,3.234486e+09,2.293666e+09,...,1.147017e+10,1.198867e+10,1.325827e+10,1.537951e+10,1.558511e+10,1.524146e+10,1.803199e+10,1.901725e+10,2.349124e+10,2.704643e+10
3,Andorra,AND,1.028990e+09,1.106891e+09,1.209992e+09,1.007090e+09,1.017544e+09,1.178745e+09,1.224024e+09,1.180646e+09,...,2.789883e+09,2.896612e+09,3.000160e+09,3.218419e+09,3.155150e+09,2.891002e+09,3.324648e+09,3.380612e+09,3.785066e+09,4.039842e+09
4,United Arab Emirates,ARE,5.070144e+10,5.155217e+10,5.423917e+10,5.562517e+10,5.930509e+10,6.574367e+10,7.357123e+10,7.883901e+10,...,3.819730e+11,3.817171e+11,4.033650e+11,4.405601e+11,4.339262e+11,3.571619e+11,4.224414e+11,5.114034e+11,5.226222e+11,5.523248e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,Samoa,WSM,1.257663e+08,1.255972e+08,1.323030e+08,1.331229e+08,2.210981e+08,2.248657e+08,2.499079e+08,2.854756e+08,...,8.241505e+08,8.439248e+08,8.848444e+08,8.784484e+08,9.129505e+08,8.688849e+08,8.597249e+08,8.895547e+08,1.044910e+09,1.175750e+09
188,Yemen,YEM,1.264382e+10,1.466545e+10,1.795937e+10,2.173680e+10,2.801948e+10,1.279635e+10,6.496164e+09,6.838299e+09,...,4.244449e+10,3.131783e+10,2.684223e+10,2.160616e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
189,South Africa,ZAF,1.260481e+11,1.352037e+11,1.469562e+11,1.471947e+11,1.535127e+11,1.717359e+11,1.632349e+11,1.689781e+11,...,3.467098e+11,3.235855e+11,3.814488e+11,4.052607e+11,3.893300e+11,3.379747e+11,4.199863e+11,4.075960e+11,3.814407e+11,4.011450e+11
190,Zambia,ZMB,3.288382e+09,3.376807e+09,3.182811e+09,3.273505e+09,3.656806e+09,3.806983e+09,3.597221e+09,4.303288e+09,...,2.125122e+10,2.095841e+10,2.587360e+10,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10
191,Zimbabwe,ZWE,8.788302e+09,8.646000e+09,6.755000e+09,6.567250e+09,6.894250e+09,7.115000e+09,8.557500e+09,8.534000e+09,...,1.997325e+10,2.055925e+10,5.103566e+10,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10

In [187]:
df_clean = df_clean.melt(id_vars=['country', 'code'], var_name='year', value_name='gdp')
df_clean['year'] = df_clean['year'].astype(int)
df_clean

                   country code  year           gdp
0              Afghanistan  AFG  1990  0.000000e+00
1                   Angola  AGO  1990  1.122952e+10
2                  Albania  ALB  1990  2.028554e+09
3                  Andorra  AND  1990  1.028990e+09
4     United Arab Emirates  ARE  1990  5.070144e+10
...                    ...  ...   ...           ...
6715                 Samoa  WSM  2024  1.175750e+09
6716                 Yemen  YEM  2024  0.000000e+00
6717          South Africa  ZAF  2024  4.011450e+11
6718                Zambia  ZMB  2024  2.530319e+10
6719              Zimbabwe  ZWE  2024  4.153941e+10

[6720 rows x 4 columns]

In [188]:
df_clean.to_csv("gdp_data_cleaned_file.csv", index=False)