In [1]:
import pandas as pd
import numpy as np

df_hdi = pd.read_excel("worldhdi.xlsx")
df_jme = pd.read_excel("JME.xlsx")

df_jme.head()

,ISO Code,Country,UN Region,UN Sub Region,SDG Region,Development Regions,UNICEF Region,UNICEF Sub-Regions,WHO Region,World Bank Income Groups,World Bank Income Groups Combined,World Bank Regions
0,AFG,Afghanistan,Asia,Southern Asia,Central Asia and Southern Asia,Least Developed,ROSA,SA,EMRO,Low Income,Low Income,South Asia
1,ALB,Albania,Europe,Southern Europe,Northern America and Europe,More Developed,ECA,EECA,EURO,Upper Middle Income,Middle Income,Europe & Central Asia
2,DZA,Algeria,Africa,Northern Africa,Western Asia and Northern Africa,Less Developed,MENA,MENA,AFRO,Upper Middle Income,Middle Income,Middle East & North Africa
3,AND,Andorra,Europe,Southern Europe,Northern America and Europe,More Developed,ECA,WE,EURO,High Income,High Income,Europe & Central Asia
4,AGO,Angola,Africa,Middle Africa,Sub-Saharan Africa,Least Developed,SSA,ESA,AFRO,Lower Middle Income,Middle Income,Sub-Saharan Africa

In [3]:
df_hdi.head()

,hdi_rank,country,hdi_1990,hdi_2000,hdi_2010,hdi_2015,hdi_2019,hdi_2020,hdi_2021,hdi_2022,rank_change_2015_2022,avg_growth_1990_2000,avg_growth_2000_2010,avg_growth_2010_2022,avg_growth_1990_2022,tier_hdi,iso3c
0,1.0,Switzerland,0.850,0.885,0.940,0.952,0.960,0.957,0.965,0.967,0.0,0.404328,0.604744,0.236267,0.403820,Very High,CHE
1,2.0,Norway,0.845,0.914,0.938,0.952,0.961,0.963,0.964,0.966,-1.0,0.788028,0.259530,0.245416,0.419086,Very High,NOR
2,3.0,Iceland,0.834,0.895,0.927,0.948,0.958,0.955,0.957,0.959,0.0,0.708401,0.351916,0.283213,0.437384,Very High,ISL
3,4.0,"Hong Kong, China (SAR)",0.739,0.831,0.914,0.936,0.953,0.955,0.959,0.956,2.0,1.180229,0.956554,0.375096,0.807808,Very High,HKG
4,5.0,Denmark,0.839,0.890,0.913,0.936,0.946,0.946,0.947,0.952,1.0,0.591852,0.255470,0.349185,0.395638,Very High,DNK

In [4]:
print("HDI columns:")
print(df_hdi.columns.tolist())

print("\nJME columns:")
print(df_jme.columns.tolist())

HDI columns:
['hdi_rank', 'country', 'hdi_1990', 'hdi_2000', 'hdi_2010', 'hdi_2015', 'hdi_2019', 'hdi_2020', 'hdi_2021', 'hdi_2022', 'rank_change_2015_2022', 'avg_growth_1990_2000', 'avg_growth_2000_2010', 'avg_growth_2010_2022', 'avg_growth_1990_2022', 'tier_hdi', 'iso3c']

JME columns:
['ISO Code', 'Country', 'UN Region', 'UN Sub Region', 'SDG Region', 'Development Regions', 'UNICEF Region', 'UNICEF Sub-Regions', 'WHO Region', 'World Bank Income Groups', 'World Bank Income Groups Combined', 'World Bank Regions']

In [5]:
df_hdi.columns = df_hdi.columns.str.strip()
df_jme.columns = df_jme.columns.str.strip()

In [6]:
print(df_hdi.columns.tolist())
print(df_jme.columns.tolist())

['hdi_rank', 'country', 'hdi_1990', 'hdi_2000', 'hdi_2010', 'hdi_2015', 'hdi_2019', 'hdi_2020', 'hdi_2021', 'hdi_2022', 'rank_change_2015_2022', 'avg_growth_1990_2000', 'avg_growth_2000_2010', 'avg_growth_2010_2022', 'avg_growth_1990_2022', 'tier_hdi', 'iso3c']
['ISO Code', 'Country', 'UN Region', 'UN Sub Region', 'SDG Region', 'Development Regions', 'UNICEF Region', 'UNICEF Sub-Regions', 'WHO Region', 'World Bank Income Groups', 'World Bank Income Groups Combined', 'World Bank Regions']

In [7]:
df_hdi["country"] = df_hdi["country"].astype(str).str.strip()
df_jme["Country"] = df_jme["Country"].astype(str).str.strip()

In [8]:
df_hdi["country"] = df_hdi["country"].replace("nan", np.nan)
df_jme["Country"] = df_jme["Country"].replace("nan", np.nan)

df_hdi = df_hdi.dropna(subset=["country"])
df_jme = df_jme.dropna(subset=["Country"])

In [9]:
country_replace = {
    "Türkiye": "Turkey",
    "Eswatini (Kingdom of)": "Swaziland",
    "Moldova (Republic of)": "Republic of Moldova",
    "Tanzania (United Republic of)": "United Republic of Tanzania",
    "Congo (Democratic Republic of the)": "Democratic Republic of the Congo",
    "Palestine, State of": "State of Palestine",
    "Korea (Republic of)": "Republic of Korea",
    "Korea (Democratic People's Rep. of)": "Democratic People's Republic of Korea",
    "North Macedonia": "The former Yugoslav Republic of Macedonia"
}

df_hdi["country"] = df_hdi["country"].replace(country_replace)

In [10]:
print(sorted(set(country_replace.values()) & set(df_hdi["country"])))

["Democratic People's Republic of Korea", 'Democratic Republic of the Congo', 'Republic of Korea', 'Republic of Moldova', 'State of Palestine', 'Swaziland', 'The former Yugoslav Republic of Macedonia', 'Turkey', 'United Republic of Tanzania']

In [11]:
hdi_countries = set(df_hdi["country"])
jme_countries = set(df_jme["Country"])

print("In HDI but not in JME:")
print(sorted(hdi_countries - jme_countries))

print("\nIn JME but not in HDI:")
print(sorted(jme_countries - hdi_countries))

In HDI but not in JME:
['Arab States', 'Developing countries', 'East Asia and the Pacific', 'Europe and Central Asia', 'High human development', 'Hong Kong, China (SAR)', 'Latin America and the Caribbean', 'Least developed countries', 'Low human development', 'Medium human development', 'Organisation for Economic Co-operation and Development', 'Small island developing states', 'South Asia', 'Sub-Saharan Africa', 'Very high human development', 'World']

In JME but not in HDI:
['Anguilla', 'British Virgin Islands', 'Cook Islands', 'Holy See', 'Montserrat', 'Niue', 'Tokelau', 'Turks and Caicos Islands']

In [12]:
df_hdi_clean = df_hdi[df_hdi["country"].isin(jme_countries)].copy()

In [13]:
print(df_hdi_clean.shape)
print(sorted(df_hdi_clean["country"].unique())[:20])

(194, 17)
['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan']

In [14]:
print(sorted(set(country_replace.values()) & set(df_hdi_clean["country"])))

["Democratic People's Republic of Korea", 'Democratic Republic of the Congo', 'Republic of Korea', 'Republic of Moldova', 'State of Palestine', 'Swaziland', 'The former Yugoslav Republic of Macedonia', 'Turkey', 'United Republic of Tanzania']

In [15]:
sorted(df_hdi_clean['country'].unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia (Plurinational State of)',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 "Côte d'Ivoire",
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran (Islamic Republic of)',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia (Federated States of)',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Republic of Korea',
 'Republic of Moldova',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'State of Palestine',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Thailand',
 'The former Yugoslav Republic of Macedonia',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United Republic of Tanzania',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela (Bolivarian Republic of)',
 'Viet Nam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [16]:
df_hdi_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 194 entries, 0 to 194
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   hdi_rank               192 non-null    float64
 1   country                194 non-null    object
 2   hdi_1990               142 non-null    float64
 3   hdi_2000               175 non-null    float64
 4   hdi_2010               190 non-null    float64
 5   hdi_2015               191 non-null    float64
 6   hdi_2019               191 non-null    float64
 7   hdi_2020               191 non-null    float64
 8   hdi_2021               191 non-null    float64
 9   hdi_2022               192 non-null    float64
 10  rank_change_2015_2022  191 non-null    float64
 11  avg_growth_1990_2000   142 non-null    float64
 12  avg_growth_2000_2010   175 non-null    float64
 13  avg_growth_2010_2022   190 non-null    float64
 14  avg_growth_1990_2022   142 non-null    float64
 15  tier_hdi               192 non-null    object
 16  iso3c                  194 non-null    object
dtypes: float64(14), object(3)
memory usage: 27.3+ KB

In [17]:
df_hdi_clean.drop(columns=[
    'rank_change_2015_2022',
    'avg_growth_1990_2000',
    'avg_growth_2000_2010',
    'avg_growth_2010_2022',
    'tier_hdi',
    'iso3c'
], inplace=True)

In [18]:
df_hdi_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 194 entries, 0 to 194
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   hdi_rank              192 non-null    float64
 1   country               194 non-null    object
 2   hdi_1990              142 non-null    float64
 3   hdi_2000              175 non-null    float64
 4   hdi_2010              190 non-null    float64
 5   hdi_2015              191 non-null    float64
 6   hdi_2019              191 non-null    float64
 7   hdi_2020              191 non-null    float64
 8   hdi_2021              191 non-null    float64
 9   hdi_2022              192 non-null    float64
 10  avg_growth_1990_2022  142 non-null    float64
dtypes: float64(10), object(1)
memory usage: 18.2+ KB

In [19]:
missing = df_hdi_clean.isna().mean()*100
missing.sort_values(ascending=False)

hdi_1990                26.804124
avg_growth_1990_2022    26.804124
hdi_2000                 9.793814
hdi_2010                 2.061856
hdi_2015                 1.546392
hdi_2019                 1.546392
hdi_2020                 1.546392
hdi_2021                 1.546392
hdi_rank                 1.030928
hdi_2022                 1.030928
country                  0.000000
dtype: float64

In [25]:
df_hdi_clean = df_hdi_clean.merge(
    df_jme[['Country','UN Region']],
    left_on='country',
    right_on='Country',
    how='left'
)

In [26]:
df_hdi_clean = df_hdi_clean.drop(columns='Country')

In [27]:
df_hdi_clean[df_hdi_clean['UN Region'].isna()]

Empty DataFrame
Columns: [hdi_rank, country, hdi_1990, hdi_2000, hdi_2010, hdi_2015, hdi_2019, hdi_2020, hdi_2021, hdi_2022, avg_growth_1990_2022, UN Region]
Index: []

In [28]:
df_hdi_clean.head(20)

,hdi_rank,country,hdi_1990,hdi_2000,hdi_2010,hdi_2015,hdi_2019,hdi_2020,hdi_2021,hdi_2022,avg_growth_1990_2022,UN Region
0,1.0,Switzerland,0.850,0.885,0.940,0.952,0.960,0.957,0.965,0.967,0.403820,Europe
1,2.0,Norway,0.845,0.914,0.938,0.952,0.961,0.963,0.964,0.966,0.419086,Europe
2,3.0,Iceland,0.834,0.895,0.927,0.948,0.958,0.955,0.957,0.959,0.437384,Europe
3,5.0,Denmark,0.839,0.890,0.913,0.936,0.946,0.946,0.947,0.952,0.395638,Europe
4,5.0,Sweden,0.808,0.903,0.910,0.937,0.947,0.944,0.949,0.952,0.513825,Europe
5,7.0,Germany,0.828,0.890,0.929,0.941,0.951,0.948,0.948,0.950,0.430451,Europe
6,7.0,Ireland,0.743,0.851,0.908,0.924,0.942,0.945,0.946,0.950,0.770975,Europe
7,9.0,Singapore,0.780,0.863,0.921,0.935,0.945,0.942,0.942,0.949,0.614741,Asia
8,10.0,Australia,0.864,0.896,0.924,0.933,0.941,0.948,0.949,0.946,0.283745,Oceania
9,10.0,Netherlands,0.847,0.892,0.917,0.932,0.941,0.938,0.941,0.946,0.346041,Europe
10,12.0,Belgium,0.814,0.884,0.913,0.924,0.936,0.930,0.938,0.942,0.457433,Europe
11,12.0,Finland,0.811,0.887,0.912,0.930,0.939,0.939,0.941,0.942,0.469025,Europe
12,12.0,Liechtenstein,NaN,0.871,0.916,0.926,0.940,0.933,0.936,0.942,NaN,Europe
13,15.0,United Kingdom,0.804,0.863,0.913,0.923,0.933,0.920,0.931,0.940,0.489571,Europe
14,16.0,New Zealand,0.812,0.894,0.924,0.933,0.937,0.935,0.936,0.939,0.455142,Oceania
15,17.0,United Arab Emirates,0.717,0.790,0.828,0.860,0.933,0.930,0.931,0.937,0.839780,Asia
16,18.0,Canada,0.861,0.890,0.911,0.927,0.932,0.928,0.934,0.935,0.257995,Northern America
17,19.0,Republic of Korea,0.731,0.824,0.890,0.908,0.922,0.922,0.926,0.929,0.751860,Asia
18,20.0,Luxembourg,0.793,0.864,0.912,0.914,0.925,0.921,0.927,0.927,0.489100,Europe
19,20.0,United States,0.875,0.894,0.916,0.924,0.933,0.923,0.921,0.927,0.180568,Northern America

In [29]:
df_hdi_clean = df_hdi_clean.rename(columns={"UN Region": "un_region"})

In [30]:
df_hdi_clean.columns

Index(['hdi_rank', 'country', 'hdi_1990', 'hdi_2000', 'hdi_2010', 'hdi_2015',
       'hdi_2019', 'hdi_2020', 'hdi_2021', 'hdi_2022', 'avg_growth_1990_2022',
       'un_region'],
      dtype='object')

In [31]:
hdi_cols = df_hdi_clean.filter(regex=r"^hdi_\d{4}$").columns
print(hdi_cols)

Index(['hdi_1990', 'hdi_2000', 'hdi_2010', 'hdi_2015', 'hdi_2019', 'hdi_2020',
       'hdi_2021', 'hdi_2022'],
      dtype='object')

In [32]:
df_long = df_hdi_clean.melt(
    id_vars=["country", "un_region"],
    value_vars=hdi_cols,
    var_name="year",
    value_name="hdi"
)

In [33]:
df_long["year"] = df_long["year"].str.extract(r"(\d{4})").astype(int)

In [34]:
missing = df_long[df_long["hdi"].isna()]
missing.head()

          country un_region  year  hdi
12  Liechtenstein    Europe  1990  NaN
21       Slovenia    Europe  1990  NaN
33        Andorra    Europe  1990  NaN
37        Croatia    Europe  1990  NaN
43       Slovakia    Europe  1990  NaN

In [35]:
missing_by_country = (
    missing.groupby("country")["year"]
    .count()
    .sort_values(ascending=False)
)

print(missing_by_country)

country
Democratic People's Republic of Korea        8
Monaco                                       8
Somalia                                      7
Marshall Islands                             3
Vanuatu                                      2
Nigeria                                      2
Saint Kitts and Nevis                        2
Lebanon                                      2
Guinea-Bissau                                2
Grenada                                      2
Eritrea                                      2
Nauru                                        2
Montenegro                                   2
Bhutan                                       2
South Sudan                                  2
State of Palestine                           2
Antigua and Barbuda                          2
Suriname                                     2
Turkmenistan                                 2
Solomon Islands                              1
Uzbekistan                                   1
Oman                                         1
Palau                                        1
Timor-Leste                                  1
Saint Vincent and the Grenadines             1
Slovenia                                     1
Samoa                                        1
The former Yugoslav Republic of Macedonia    1
Serbia                                       1
Seychelles                                   1
Slovakia                                     1
Andorra                                      1
Micronesia (Federated States of)             1
Angola                                       1
Azerbaijan                                   1
Belarus                                      1
Bosnia and Herzegovina                       1
Burkina Faso                                 1
Cabo Verde                                   1
Chad                                         1
Comoros                                      1
Croatia                                      1
Djibouti                                     1
Dominica                                     1
Equatorial Guinea                            1
Ethiopia                                     1
Georgia                                      1
Kiribati                                     1
Liberia                                      1
Liechtenstein                                1
Madagascar                                   1
Maldives                                     1
Name: year, dtype: int64

In [36]:
missing_years_by_country = (
    missing.groupby("country")["year"]
    .apply(list)
)

print(missing_years_by_country)

country
Andorra                                                                                [1990]
Angola                                                                                 [1990]
Antigua and Barbuda                                                              [1990, 2000]
Azerbaijan                                                                             [1990]
Belarus                                                                                [1990]
Bhutan                                                                           [1990, 2000]
Bosnia and Herzegovina                                                                 [1990]
Burkina Faso                                                                           [1990]
Cabo Verde                                                                             [1990]
Chad                                                                                   [1990]
Comoros                                                                                [1990]
Croatia                                                                                [1990]
Democratic People's Republic of Korea        [1990, 2000, 2010, 2015, 2019, 2020, 2021, 2022]
Djibouti                                                                               [1990]
Dominica                                                                               [1990]
Equatorial Guinea                                                                      [1990]
Eritrea                                                                          [1990, 2000]
Ethiopia                                                                               [1990]
Georgia                                                                                [1990]
Grenada                                                                          [1990, 2000]
Guinea-Bissau                                                                    [1990, 2000]
Kiribati                                                                               [1990]
Lebanon                                                                          [1990, 2000]
Liberia                                                                                [1990]
Liechtenstein                                                                          [1990]
Madagascar                                                                             [1990]
Maldives                                                                               [1990]
Marshall Islands                                                           [1990, 2000, 2010]
Micronesia (Federated States of)                                                       [1990]
Monaco                                       [1990, 2000, 2010, 2015, 2019, 2020, 2021, 2022]
Montenegro                                                                       [1990, 2000]
Nauru                                                                            [1990, 2000]
Nigeria                                                                          [1990, 2000]
Oman                                                                                   [1990]
Palau                                                                                  [1990]
Saint Kitts and Nevis                                                            [1990, 2000]
Saint Vincent and the Grenadines                                                       [1990]
Samoa                                                                                  [1990]
Serbia                                                                                 [1990]
Seychelles                                                                             [1990]
Slovakia                                                                               [1990]
Slovenia                                                                               [1990]
Solomon Islands                                                                        [1990]
Somalia                                            [1990, 2000, 2010, 2015, 2019, 2020, 2021]
South Sudan                                                                      [1990, 2000]
State of Palestine                                                               [1990, 2000]
Suriname                                                                         [1990, 2000]
The former Yugoslav Republic of Macedonia                                              [1990]
Timor-Leste                                                                            [1990]
Turkmenistan                                                                     [1990, 2000]
Uzbekistan                                                                             [1990]
Vanuatu                                                                          [1990, 2000]
Name: year, dtype: object

In [37]:
missing_by_year = (
    missing.groupby("year")["country"]
    .count()
)

print(missing_by_year)

year
1990    52
2000    19
2010     4
2015     3
2019     3
2020     3
2021     3
2022     2
Name: country, dtype: int64

In [39]:
missing_region_year = (
    missing.groupby(["un_region","year"])["country"]
    .count()
)

print(missing_region_year)

un_region                        year
Africa                           1990    16
                                 2000     5
                                 2010     1
                                 2015     1
                                 2019     1
                                 2020     1
                                 2021     1
Asia                             1990    11
                                 2000     5
                                 2010     1
                                 2015     1
                                 2019     1
                                 2020     1
                                 2021     1
                                 2022     1
Europe                           1990    11
                                 2000     2
                                 2010     1
                                 2015     1
                                 2019     1
                                 2020     1
                                 2021     1
                                 2022     1
Latin America and the Caribbean  1990     6
                                 2000     4
Oceania                          1990     8
                                 2000     3
                                 2010     1
Name: country, dtype: int64

In [41]:
coverage = (
    df_long.groupby(["un_region","year"])["hdi"]
    .count()
    .reset_index(name="num_values")
)

print(coverage)

                          un_region  year  num_values
0                            Africa  1990          38
1                            Africa  2000          49
2                            Africa  2010          53
3                            Africa  2015          53
4                            Africa  2019          53
5                            Africa  2020          53
6                            Africa  2021          53
7                            Africa  2022          54
8                              Asia  1990          37
9                              Asia  2000          43
10                             Asia  2010          47
11                             Asia  2015          47
12                             Asia  2019          47
13                             Asia  2020          47
14                             Asia  2021          47
15                             Asia  2022          47
16                           Europe  1990          32
17                           Europe  2000          41
18                           Europe  2010          42
19                           Europe  2015          42
20                           Europe  2019          42
21                           Europe  2020          42
22                           Europe  2021          42
23                           Europe  2022          42
24  Latin America and the Caribbean  1990          27
25  Latin America and the Caribbean  2000          29
26  Latin America and the Caribbean  2010          33
27  Latin America and the Caribbean  2015          33
28  Latin America and the Caribbean  2019          33
29  Latin America and the Caribbean  2020          33
30  Latin America and the Caribbean  2021          33
31  Latin America and the Caribbean  2022          33
32                 Northern America  1990           2
33                 Northern America  2000           2
34                 Northern America  2010           2
35                 Northern America  2015           2
36                 Northern America  2019           2
37                 Northern America  2020           2
38                 Northern America  2021           2
39                 Northern America  2022           2
40                          Oceania  1990           6
41                          Oceania  2000          11
42                          Oceania  2010          13
43                          Oceania  2015          14
44                          Oceania  2019          14
45                          Oceania  2020          14
46                          Oceania  2021          14
47                          Oceania  2022          14

In [42]:
df_hdi_clean.to_csv("hdi_clean.csv", index=False)

In [43]:

import statsmodels.formula.api as smf


# =========================================================
# 1. LOAD CLEAN DATASET
# =========================================================

df_hdi_clean = pd.read_csv("hdi_clean.csv")

# Clean column names
df_hdi_clean.columns = df_hdi_clean.columns.str.strip()

# Ensure key columns are clean
df_hdi_clean["country"] = df_hdi_clean["country"].astype(str).str.strip()
df_hdi_clean["un_region"] = df_hdi_clean["un_region"].astype(str).str.strip()


# =========================================================
# 2. IDENTIFY HDI COLUMNS
# =========================================================

hdi_cols = df_hdi_clean.filter(regex=r"^hdi_\d{4}$").columns.tolist()

print("HDI columns found:")
print(hdi_cols)


# =========================================================
# 3. RESHAPE TO LONG FORMAT
# =========================================================

df_long = df_hdi_clean.melt(
    id_vars=["country", "un_region"],
    value_vars=hdi_cols,
    var_name="year",
    value_name="hdi"
)

df_long["year"] = df_long["year"].str.extract(r"(\d{4})").astype(int)
df_long = df_long.sort_values(["country", "year"]).reset_index(drop=True)


# =========================================================
# 4. KEEP TRACK OF ORIGINAL MISSING VALUES
# =========================================================

df_long["hdi_original"] = df_long["hdi"]
df_long["imputed_flag"] = 0
df_long["imputation_method"] = np.nan


# =========================================================
# 5. METHOD 1 — TEMPORAL INTERPOLATION / EXTRAPOLATION
# =========================================================
# This uses each country's own time series first

df_long["hdi_temp"] = (
    df_long.groupby("country")["hdi"]
    .transform(lambda x: x.interpolate(limit_direction="both"))
)

mask_temp = df_long["hdi"].isna() & df_long["hdi_temp"].notna()

df_long.loc[mask_temp, "hdi"] = df_long.loc[mask_temp, "hdi_temp"]
df_long.loc[mask_temp, "imputed_flag"] = 1
df_long.loc[mask_temp, "imputation_method"] = "temporal_interpolation"


# =========================================================
# 6. METHOD 2 — PANEL REGRESSION
# =========================================================
# Fit model only on observed values after temporal interpolation step
# We use original observed values + still-missing rows remain missing

df_model = df_long.dropna(subset=["hdi"]).copy()

# Exclude countries with all values originally missing from model prediction if desired
all_missing_countries = (
    df_long.groupby("country")["hdi_original"]
    .apply(lambda x: x.isna().all())
)
all_missing_countries = set(all_missing_countries[all_missing_countries].index)

# Fit panel-style regression
model = smf.ols(
    "hdi ~ C(country) + C(un_region) + year",
    data=df_model
).fit()

mask_panel = df_long["hdi"].isna() & ~df_long["country"].isin(all_missing_countries)

if mask_panel.sum() > 0:
    df_long.loc[mask_panel, "hdi"] = model.predict(df_long.loc[mask_panel])
    df_long.loc[mask_panel, "imputed_flag"] = 1
    df_long.loc[mask_panel, "imputation_method"] = "panel_regression"


# =========================================================
# 7. METHOD 3 — REGIONAL-TEMPORAL SMOOTHING
# =========================================================
# For any values still missing:
# hdi = regional mean(year) + country average offset from region

regional_mean = (
    df_long.groupby(["un_region", "year"])["hdi"]
    .mean()
    .rename("regional_mean")
)

tmp = df_long.merge(
    regional_mean.reset_index(),
    on=["un_region", "year"],
    how="left"
)

tmp["offset"] = tmp["hdi"] - tmp["regional_mean"]

country_offset = (
    tmp.groupby("country")["offset"]
    .mean()
    .rename("country_offset")
)

tmp = tmp.merge(
    country_offset.reset_index(),
    on="country",
    how="left"
)

mask_rts = tmp["hdi"].isna()

# Fill with regional mean + country offset when available
tmp.loc[mask_rts, "hdi_fill_rts"] = (
    tmp.loc[mask_rts, "regional_mean"] + tmp.loc[mask_rts, "country_offset"].fillna(0)
)

mask_rts_valid = tmp["hdi"].isna() & tmp["hdi_fill_rts"].notna()

tmp.loc[mask_rts_valid, "hdi"] = tmp.loc[mask_rts_valid, "hdi_fill_rts"]
tmp.loc[mask_rts_valid, "imputed_flag"] = 1
tmp.loc[mask_rts_valid, "imputation_method"] = "regional_temporal_smoothing"

df_long = tmp.copy()


# =========================================================
# 8. FALLBACK — REGIONAL MEAN ONLY
# =========================================================

regional_mean_fallback = (
    df_long.groupby(["un_region", "year"])["hdi"]
    .mean()
    .rename("regional_mean_fallback")
)

df_long = df_long.merge(
    regional_mean_fallback.reset_index(),
    on=["un_region", "year"],
    how="left"
)

mask_regional = df_long["hdi"].isna() & df_long["regional_mean_fallback"].notna()

df_long.loc[mask_regional, "hdi"] = df_long.loc[mask_regional, "regional_mean_fallback"]
df_long.loc[mask_regional, "imputed_flag"] = 1
df_long.loc[mask_regional, "imputation_method"] = "regional_mean_fallback"


# =========================================================
# 9. OPTIONAL — FLAG EXTREME CASES STILL MISSING
# =========================================================

mask_still_missing = df_long["hdi"].isna()

df_long.loc[mask_still_missing, "imputation_method"] = "not_imputed"


# =========================================================
# 10. CLIP VALUES TO VALID HDI RANGE
# =========================================================

df_long["hdi"] = df_long["hdi"].clip(lower=0, upper=1)


# =========================================================
# 11. DIAGNOSTICS
# =========================================================

print("\nRemaining missing values after imputation:")
print(df_long["hdi"].isna().sum())

print("\nImputation method counts:")
print(df_long["imputation_method"].value_counts(dropna=False))

print("\nCountries still missing after all methods:")
print(df_long.loc[df_long["hdi"].isna(), "country"].drop_duplicates().sort_values().tolist())


# =========================================================
# 12. RESHAPE BACK TO WIDE FORMAT
# =========================================================

df_hdi_imputed = df_long.pivot(
    index=["country", "un_region"],
    columns="year",
    values="hdi"
).reset_index()

# Rename year columns back to hdi_YYYY format
df_hdi_imputed.columns = [
    f"hdi_{col}" if isinstance(col, int) else col
    for col in df_hdi_imputed.columns
]


# =========================================================
# 13. CREATE IMPUTATION AUDIT TABLE
# =========================================================

imputation_audit = df_long.loc[df_long["imputed_flag"] == 1, [
    "country", "un_region", "year", "hdi_original", "hdi", "imputation_method"
]].copy()

imputation_audit = imputation_audit.rename(columns={
    "hdi": "hdi_filled"
}).sort_values(["country", "year"])


# =========================================================
# 14. SAVE OUTPUTS
# =========================================================

df_hdi_imputed.to_csv("hdi_imputed.csv", index=False)
imputation_audit.to_csv("hdi_imputation_audit.csv", index=False)

print("\nSaved files:")
print("- hdi_imputed.csv")
print("- hdi_imputation_audit.csv")

HDI columns found:
['hdi_1990', 'hdi_2000', 'hdi_2010', 'hdi_2015', 'hdi_2019', 'hdi_2020', 'hdi_2021', 'hdi_2022']

Remaining missing values after imputation:
0

Imputation method counts:
imputation_method
NaN                            1463
temporal_interpolation           73
regional_temporal_smoothing      16
Name: count, dtype: int64

Countries still missing after all methods:
[]

Saved files:
- hdi_imputed.csv
- hdi_imputation_audit.csv

C:\Users\Utilizador\AppData\Local\Temp\ipykernel_7800\923102876.py:66: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'temporal_interpolation' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_long.loc[mask_temp, "imputation_method"] = "temporal_interpolation"

In [44]:
df_c_hdi = pd.read_csv("hdi_imputed.csv")
df_c_hdi.head(20)

,country,un_region,hdi_1990,hdi_2000,hdi_2010,hdi_2015,hdi_2019,hdi_2020,hdi_2021,hdi_2022
0,Afghanistan,Asia,0.284,0.340,0.449,0.479,0.492,0.488,0.473,0.462
1,Albania,Europe,0.649,0.678,0.766,0.797,0.800,0.784,0.785,0.789
2,Algeria,Africa,0.593,0.652,0.721,0.736,0.742,0.730,0.740,0.745
3,Andorra,Europe,0.815,0.815,0.863,0.856,0.865,0.843,0.855,0.884
4,Angola,Africa,0.380,0.380,0.516,0.591,0.597,0.594,0.590,0.591
5,Antigua and Barbuda,Latin America and the Caribbean,0.808,0.808,0.808,0.818,0.831,0.820,0.819,0.826
6,Argentina,Latin America and the Caribbean,0.724,0.780,0.834,0.850,0.853,0.841,0.844,0.849
7,Armenia,Asia,0.658,0.656,0.739,0.769,0.789,0.769,0.774,0.786
8,Australia,Oceania,0.864,0.896,0.924,0.933,0.941,0.948,0.949,0.946
9,Austria,Europe,0.823,0.870,0.903,0.910,0.920,0.916,0.920,0.926
10,Azerbaijan,Asia,0.635,0.635,0.733,0.751,0.762,0.722,0.738,0.760
11,Bahamas,Latin America and the Caribbean,0.760,0.788,0.800,0.807,0.802,0.798,0.799,0.820
12,Bahrain,Asia,0.733,0.775,0.807,0.859,0.888,0.884,0.884,0.888
13,Bangladesh,Asia,0.399,0.491,0.558,0.604,0.646,0.657,0.662,0.670
14,Barbados,Latin America and the Caribbean,0.728,0.760,0.792,0.798,0.806,0.803,0.803,0.809
15,Belarus,Europe,0.708,0.708,0.790,0.809,0.810,0.800,0.801,0.801
16,Belgium,Europe,0.814,0.884,0.913,0.924,0.936,0.930,0.938,0.942
17,Belize,Latin America and the Caribbean,0.609,0.657,0.720,0.714,0.718,0.705,0.698,0.700
18,Benin,Africa,0.350,0.412,0.481,0.509,0.506,0.501,0.502,0.504
19,Bhutan,Asia,0.582,0.582,0.582,0.625,0.668,0.675,0.677,0.681

In [45]:
df_c_hdi.tail(20)

,country,un_region,hdi_1990,hdi_2000,hdi_2010,hdi_2015,hdi_2019,hdi_2020,hdi_2021,hdi_2022
174,Tonga,Oceania,0.640,0.679,0.709,0.723,0.740,0.742,0.738,0.739
175,Trinidad and Tobago,Latin America and the Caribbean,0.656,0.708,0.785,0.812,0.813,0.815,0.804,0.814
176,Tunisia,Africa,0.566,0.651,0.713,0.724,0.740,0.734,0.729,0.732
177,Turkey,Asia,0.598,0.669,0.750,0.821,0.842,0.835,0.841,0.855
178,Turkmenistan,Asia,0.699,0.699,0.699,0.725,0.732,0.731,0.740,0.744
179,Tuvalu,Oceania,0.564,0.599,0.623,0.656,0.654,0.655,0.653,0.653
180,Uganda,Africa,0.329,0.392,0.500,0.525,0.544,0.545,0.545,0.550
181,Ukraine,Europe,0.731,0.698,0.766,0.764,0.774,0.762,0.755,0.734
182,United Arab Emirates,Asia,0.717,0.790,0.828,0.860,0.933,0.930,0.931,0.937
183,United Kingdom,Europe,0.804,0.863,0.913,0.923,0.933,0.920,0.931,0.940
184,United Republic of Tanzania,Africa,0.366,0.396,0.493,0.507,0.533,0.535,0.529,0.532
185,United States,Northern America,0.875,0.894,0.916,0.924,0.933,0.923,0.921,0.927
186,Uruguay,Latin America and the Caribbean,0.702,0.754,0.785,0.807,0.818,0.820,0.814,0.830
187,Uzbekistan,Asia,0.603,0.603,0.675,0.701,0.725,0.716,0.721,0.727
188,Vanuatu,Oceania,0.578,0.578,0.578,0.592,0.614,0.612,0.614,0.614
189,Venezuela (Bolivarian Republic of),Latin America and the Caribbean,0.657,0.699,0.759,0.766,0.720,0.691,0.690,0.699
190,Viet Nam,Asia,0.492,0.599,0.676,0.697,0.717,0.726,0.718,0.726
191,Yemen,Asia,0.357,0.434,0.496,0.455,0.430,0.430,0.425,0.424
192,Zambia,Africa,0.417,0.418,0.528,0.563,0.574,0.569,0.565,0.569
193,Zimbabwe,Africa,0.479,0.426,0.481,0.544,0.560,0.554,0.549,0.550

In [46]:
hdi_cols = df_c_hdi.filter(regex=r"^hdi_\d{4}$").columns
print(hdi_cols)

Index(['hdi_1990', 'hdi_2000', 'hdi_2010', 'hdi_2015', 'hdi_2019', 'hdi_2020',
       'hdi_2021', 'hdi_2022'],
      dtype='object')

In [47]:
df_hdi_long = df_c_hdi.melt(
    id_vars=["country", "un_region"],
    value_vars=hdi_cols,
    var_name="year",
    value_name="hdi"
)

In [48]:
df_hdi_long.head(20)

                country                        un_region      year    hdi
0           Afghanistan                             Asia  hdi_1990  0.284
1               Albania                           Europe  hdi_1990  0.649
2               Algeria                           Africa  hdi_1990  0.593
3               Andorra                           Europe  hdi_1990  0.815
4                Angola                           Africa  hdi_1990  0.380
5   Antigua and Barbuda  Latin America and the Caribbean  hdi_1990  0.808
6             Argentina  Latin America and the Caribbean  hdi_1990  0.724
7               Armenia                             Asia  hdi_1990  0.658
8             Australia                          Oceania  hdi_1990  0.864
9               Austria                           Europe  hdi_1990  0.823
10           Azerbaijan                             Asia  hdi_1990  0.635
11              Bahamas  Latin America and the Caribbean  hdi_1990  0.760
12              Bahrain                             Asia  hdi_1990  0.733
13           Bangladesh                             Asia  hdi_1990  0.399
14             Barbados  Latin America and the Caribbean  hdi_1990  0.728
15              Belarus                           Europe  hdi_1990  0.708
16              Belgium                           Europe  hdi_1990  0.814
17               Belize  Latin America and the Caribbean  hdi_1990  0.609
18                Benin                           Africa  hdi_1990  0.350
19               Bhutan                             Asia  hdi_1990  0.582

In [49]:
df_hdi_long["year"] = df_hdi_long["year"].str.replace("hdi_", "").astype(int)

In [50]:
df_hdi_long = df_hdi_long.sort_values(
    ["un_region", "country", "year"]
).reset_index(drop=True)

In [51]:
df_hdi_long.head(20)

    country un_region  year    hdi
0   Algeria    Africa  1990  0.593
1   Algeria    Africa  2000  0.652
2   Algeria    Africa  2010  0.721
3   Algeria    Africa  2015  0.736
4   Algeria    Africa  2019  0.742
5   Algeria    Africa  2020  0.730
6   Algeria    Africa  2021  0.740
7   Algeria    Africa  2022  0.745
8    Angola    Africa  1990  0.380
9    Angola    Africa  2000  0.380
10   Angola    Africa  2010  0.516
11   Angola    Africa  2015  0.591
12   Angola    Africa  2019  0.597
13   Angola    Africa  2020  0.594
14   Angola    Africa  2021  0.590
15   Angola    Africa  2022  0.591
16    Benin    Africa  1990  0.350
17    Benin    Africa  2000  0.412
18    Benin    Africa  2010  0.481
19    Benin    Africa  2015  0.509

In [52]:
print(df_hdi_long.shape)

(1552, 4)

In [58]:
df_hdi_long = df_hdi_long.sort_values(
    ["year", "country"]
).reset_index(drop=True)

df_hdi_long.head()

       country un_region  year    hdi
0  Afghanistan      Asia  1990  0.284
1      Albania    Europe  1990  0.649
2      Algeria    Africa  1990  0.593
3      Andorra    Europe  1990  0.815
4       Angola    Africa  1990  0.380

In [59]:
df_hdi_long = df_hdi_long[
    ["year", "country", "un_region", "hdi"]
]

In [60]:
df_hdi_long.groupby("year")["country"].nunique()

year
1990    194
2000    194
2010    194
2015    194
2019    194
2020    194
2021    194
2022    194
Name: country, dtype: int64

In [57]:
df_hdi_long.groupby("un_region")["hdi"].mean().sort_values(ascending=False)

un_region
Northern America                   0.914438
Europe                             0.852146
Latin America and the Caribbean    0.723686
Asia                               0.704989
Oceania                            0.686250
Africa                             0.520873
Name: hdi, dtype: float64